Lesson 10
antokh1v/fefu_backend_3_6 pull request #11
Opened 2022-06-22 06:45 UTC by antokh1v

Не могу понять почему всегда получаю ошибку The modifications field is required.

2022-06-22 06:52 UTC, chrn-feip requested changes

2022-06-22 06:52 UTC, chrn-feip commented on merch-shop/app/Models/Cart.php
> +            $cartItem->price_total = $cartItem->price_item * $cartItem->quantity;
Ещё нужно считать $this->price_total накопительным итогом. И перед foreach сбросить значение в 0.

2022-06-22 06:52 UTC, chrn-feip commented on merch-shop/app/Http/Kernel.php
> +        'auth.optional' => \App\Http\Middleware\MaybeAuthenticate::class,
Нужны ещё изменения в  $middlewareGroups выше

2022-06-22 06:52 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/CartApiController.php
> +    public function show(): CartResource
Не хватает описания для документации API

2022-06-22 06:52 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/CartApiController.php
> +    public function setQuantity(CartModificationRequest $request): CartResource
Не хватает описания для документации API

2022-06-22 06:52 UTC, chrn-feip commented on merch-shop/routes/api.php
> +Route::post('/cart/set_quantity', [CartApiController::class, 'setQuantity'])->name('setQuantity');
name не нужно, если вы нигде не используете метод route с указанием этого имени

2022-06-22 11:10 UTC, chrn-feip requested changes

2022-06-22 11:10 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/CartApiController.php
> +    #[OpenApi\Response(factory: ShowCartResponse::class, statusCode: 200)]
Может быть ещё ответ с ошибками, если валидация не прошла

2022-06-22 11:10 UTC, chrn-feip commented on merch-shop/app/Models/Cart.php
> +            $this->price_total = $cartItem->price_item * $cartItem->quantity;
Нет. Верните строку про $cartItem->price_total на место. При пересчёте корзины вам нужно посчитать тотал для каждого товара в ней (это $cartItem->price_total) и тотал по всей корзине целиком ($this->price_total, это сумма всех тоталов всех товаров).

2022-06-22 12:04 UTC, chrn-feip requested changes

2022-06-22 12:04 UTC, chrn-feip commented on merch-shop/app/Models/Cart.php
> +            $cartItem->price_total = $cartItem->price_item * $cartItem->quantity;
Внимательно читаем весь комментарий :)

2022-06-22 12:04 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/CartApiController.php
> +    #[OpenApi\Response(factory: ShowCartResponse::class, statusCode: 200)]
Ещё актуально

2022-06-22 13:43 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/CartApiController.php
> +    #[OpenApi\Response(factory: ShowCartResponse::class, statusCode: 200)]
А документацию к апи перегенерировать?

2022-06-23 01:12 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/CartApiController.php
> +    #[OpenApi\Response(factory: ShowCartResponse::class, statusCode: 200)]
@antokh1v

2022-06-23 02:13 UTC, antokh1v commented on merch-shop/app/Http/Controllers/CartApiController.php
> +    #[OpenApi\Response(factory: ShowCartResponse::class, statusCode: 200)]
Понял, перегенирую. Забыл

2022-06-23 02:34 UTC, merged