Lesson 3
antokh1v/fefu_backend_3_6 pull request #4
Opened 2022-04-10 08:33 UTC by antokh1v

2022-04-11 05:28 UTC, tonighty requested changes

2022-04-11 05:28 UTC, tonighty commented on merch-shop/app/Http/Requests/StoreNewsRequest.php
> +class StoreNewsRequest extends FormRequest
эт не надо

2022-04-11 05:28 UTC, tonighty commented on merch-shop/app/Http/Requests/UpdateNewsRequest.php
> +class UpdateNewsRequest extends FormRequest
эт не надо

2022-04-11 05:28 UTC, tonighty commented on merch-shop/app/Policies/NewsPolicy.php
> +class NewsPolicy
эт не надо

2022-04-11 05:29 UTC, tonighty commented
здесь же ниче не сделано 💁🏿. запрашивай ревью, когда все сделаешь

2022-05-12 09:08 UTC, chrn-feip commented
@tonighty а тут когда будет проверено?

2022-05-12 09:17 UTC, tonighty commented
> @tonighty а тут когда будет проверено?

@chrn-feip оно проверено))

2022-05-12 11:45 UTC, chrn-feip commented
> > @tonighty а тут когда будет проверено?
> 
> @chrn-feip оно проверено))

![image](https://user-images.githubusercontent.com/40585429/168067560-aaa5cb16-e461-4e63-b2b5-1b38e985a355.png)
после твоего коммента был коммит. Что-то изменилось? Что-то от исполнителя требуется?

2022-05-12 11:52 UTC, tonighty commented on merch-shop/app/Http/Requests/StoreNewsRequest.php
> +class StoreNewsRequest extends FormRequest
@antokh1v

2022-05-12 11:52 UTC, tonighty commented on merch-shop/app/Http/Requests/UpdateNewsRequest.php
> +class UpdateNewsRequest extends FormRequest
@antokh1v

2022-05-12 11:52 UTC, tonighty commented on merch-shop/app/Policies/NewsPolicy.php
> +class NewsPolicy
@antokh1v

2022-05-15 08:13 UTC, merged