Lesson 4
antokh1v/fefu_backend_3_6 pull request #5
Opened 2022-05-11 10:29 UTC by antokh1v

2022-05-11 13:43 UTC, chrn-feip requested changes
Доведите до сдачи ДЗ 3 и сделайте потом ребейз этой ветки, чтобы остался коммит только с ДЗ 4

2022-05-11 13:43 UTC, chrn-feip commented on merch-shop/api-docs.json
> +  [41;1m Error [49;22m
А вы смотрели вообще результат генерации документации?

2022-05-12 01:43 UTC, antokh1v commented on merch-shop/api-docs.json
> +  [41;1m Error [49;22m
Я смотрел и видел что не сгенерировалось, но ошибку найти так и не смог.

2022-05-12 02:07 UTC, chrn-feip requested changes

2022-05-12 02:07 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/AppealApiController.php
> +    #[OpenApi\Parameters(factory: AppealParameters::class)]
Попробуйте это переместить выше обоих Response

2022-05-12 02:07 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/AppealApiController.php
> +    #[OpenApi\Operation(tags: ["appeal"], method: "POST")]
попробуйте тут одинарные кавычки

2022-05-12 02:07 UTC, chrn-feip commented on merch-shop/api-docs.json
> +  [41;1m Error [49;22m
Попробуйте запустить в этой ветке `sail composer dump-autoload` и повторно запустите команду генерации документации, предварительно внесите правки в контроллере.

2022-05-12 08:40 UTC, antokh1v commented on merch-shop/app/Http/Controllers/AppealApiController.php
> +    #[OpenApi\Operation(tags: ["appeal"], method: "POST")]
Все сделал, к сожалению не помогло.

2022-05-12 09:09 UTC, chrn-feip commented on merch-shop/app/Http/Controllers/AppealApiController.php
> +    #[OpenApi\Operation(tags: ["appeal"], method: "POST")]
А в предыдущем ДЗ генерация документации работала? Переключитесь туда, проверьте, может быть проблема ещё там закралась.

2022-05-13 06:45 UTC, antokh1v commented on merch-shop/app/Http/Controllers/AppealApiController.php
> +    #[OpenApi\Operation(tags: ["appeal"], method: "POST")]
Да я переключался и генерировал api-docks там. Все работает в ветке третьего урока.

2022-05-13 12:02 UTC, chrn-feip approved these changes

2022-05-15 12:03 UTC, merged