Lesson 6: Add OAuth.
antokh1v/fefu_backend_3_6 pull request #7
Opened 2022-05-21 10:45 UTC by antokh1v

2022-05-22 05:32 UTC, chrn-feip requested changes

2022-05-22 05:32 UTC, chrn-feip commented on merch-shop/database/migrations/2022_05_19_084727_add_user_oauth_fields.php
> +            $table->dropColumn(['github_id', 'github_logged_in_at', 'github_registered_at', 'discord_id',
Как сюда просочился дискорд?

2022-05-22 05:32 UTC, chrn-feip commented on merch-shop/database/migrations/2022_05_21_062207_rename_vk_to_vkontakte.php
> +            //
Где код обратного переименования полей?

2022-05-22 05:32 UTC, chrn-feip commented on merch-shop/resources/views/profile.blade.php
> +<div>
Так же нужно показать дату-время логина и регистрации в самом приложении (app_*)

2022-05-23 03:17 UTC, antokh1v commented on merch-shop/database/migrations/2022_05_21_062207_rename_vk_to_vkontakte.php
> +            //
Мне лучше откатить миграцию или сделать новую? Переписывать же сделанные миграции нельзя?

2022-05-23 03:23 UTC, chrn-feip commented on merch-shop/database/migrations/2022_05_21_062207_rename_vk_to_vkontakte.php
> +            //
Откат миграции в данном случае ничего не сделает как раз, потому что у вас ошибка. Сделайте откат, удалите файл миграции, вручную переименуйте поля, сделайте новую миграцию.

2022-05-23 03:49 UTC, antokh1v commented on merch-shop/database/migrations/2022_05_21_062207_rename_vk_to_vkontakte.php
> +            //
А метод down можно переписывать в миграции?

2022-05-23 03:53 UTC, chrn-feip commented on merch-shop/database/migrations/2022_05_21_062207_rename_vk_to_vkontakte.php
> +            //
В вашем случае можно: откатить, вручную переименовать, дописать down, применить снова. Если бы код этой миграции был бы уже в master, то нельзя. Только новая миграция.

2022-05-23 04:13 UTC, merged